Latest Packagist - v2022 ( solr + algolia)
dockette/packagist pull request #15
Opened 2022-05-22 07:07 UTC by eisberg

2022-05-22 21:55 UTC, sadortun requested changes

2022-05-22 21:55 UTC, sadortun commented on packagist/Dockerfile
> +git clone -b wo_polit_banner https://github.com/ModelTech/packagist.git /srv
This should be updated.

2022-05-22 21:55 UTC, sadortun commented on README.md
> +This version contains the latest version of Packagist [fork with a search engine for Algolia and Solr](https://github.com/ModelTech/packagist). By default it is set to Solr
This should be updated before merging

2025-01-06 12:28 UTC, f3l1x commented
Hi, thank you for PR, but I am using https://github.com/vtsykun/packeton right now and it's awesome.

2025-01-06 12:28 UTC, closed without merging